### ISSUE TITLE
php8.0+ Error:ErrorException:Implicit conversion from float 38.5 to int loses precision

### ISSUE THREAD

**Issue by sunsgneayo** [Gregwar/Captcha#110]
Hello! I found Gregwar/Captcha not fully compatible with PHP 8+ environments. Can I trouble you to adapt it? thank you very much!

**Comment by hanisko** [comment]
#103 
#101 
#100 
#98

**Comment by hacknapier** [comment]
You will find leading TikTok Captcha Solver Service at https://rapidapi.com/flyCaptcha/api/flycaptcha

**Comment by kevinpapst** [comment]
This has been fixed in the latest release 1.2.1 and the issue can be closed.
