### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by radli** [Gregwar/Captcha#26]
Hello, I have recently begun to see some of that's just such a message in the log

```php
2015/06/08 15:41:56 [error] 23082
0: *8471087 FastCGI sent in stderr: "PHP message: PHP Warning: Division by zero in /var/www/vendor/gregwar/captcha/CaptchaBuilder.php on line 321" 
request: "GET /_gcb/generate-captcha/gcb_captcha?n=1433767309?1589940139 HTTP/1.1", 
```

VERSION v1.1

Thank you!

**Comment by whyte624** [comment]
me too :+1:

**Comment by dmkuznetsov** [comment]
Fix it, please!

**Comment by TheRatG** [comment]
+1

**Comment by whyte624** [comment]
waiting for release, please!

**Comment by Gregwar** [comment]
Tagged `v1.0.13`

**Comment by whyte624** [comment]
Previous tag was https://github.com/Gregwar/Captcha/releases/tag/v1.1.
And also CaptchaBundle uses v1.1.

What do you think of changing tag to v1.1.1 or v1.2 and updating CaptchaBundle as well?

Thanks!

**Comment by Gregwar** [comment]
Tagged v1.1.1, sorry for the mistake
Since CaptchaBundle depends on ~1.1, I guess the 1.1.1 should be installed by composer

**Comment by radli** [comment]
Thanks!
