### ISSUE TITLE
setBackgroundColor(r,g,b) 不生效

### ISSUE THREAD

**Issue by zongmi** [Gregwar/Captcha#40]
$builder = new CaptchaBuilder();
        $builder->build(215,80);

        $builder->setBackgroundColor(0,0,0);

        $builder->setIgnoreAllEffects(false);
        $code=$builder->getPhrase();
        header("Cache-Control: no-cache, must-revalidate");
        header('Content-Type: image/jpeg');
        $builder->output();

**Comment by zongmi** [comment]
e 我的问题

    $builder->setBackgroundColor(0,0,0);

    $builder->build(215,80);

**Comment by Gregwar** [comment]
Can you explain your problem in english please? I don't understand what you mean
Thanks you

**Comment by atianbang** [comment]
@Gregwar  zongmi's problem is ```$builder->setBackgroundColor(0,0,0);``` not working.
@zongmi  you need call ``` $builder->setBackgroundColor(0,0,0)``` before ``` $builder->build(215,80)```
because build means this image is builded,after the image is builded,change the backgroundcolor make no sence(必须在build之前setColor,图片都build出来了再set没有意义)
