### ISSUE TITLE
maybe use mbstring in `CaptchaBuilder.php` and give additional params to accept font offset for other fonts

### ISSUE THREAD

**Issue by di3663** [Gregwar/Captcha#41]
I have change this in my copy to use my font，it works.

strlen($phrase) => mb_strlen($phrase)
$phrase[$i] => mb_substr($phrase, $i, 1)

![t31pgox 0 n 7ur8y_i3 3](https://user-images.githubusercontent.com/20258455/30310897-5e8418fa-97c5-11e7-8347-a64a44da8efc.png)

**Comment by Gregwar** [comment]
OK, You mean that you want to be able to build CAPTCHAs using extended characters, right?
Would you mind opening a PR for this?

**Comment by di3663** [comment]
@Gregwar 

OK
