### ISSUE TITLE
I created Yii Extension for this library

### ISSUE THREAD

**Issue by juliardi** [Gregwar/Captcha#48]
Hi, thanks for developing this library. 
I want to tell you that I've made an extension for Yii framework based on this library. Here is the repository [yii2-captcha](https://github.com/juliardi/yii2-captcha). I hope you like it.
If there are any problem please file an issue in that repository.

Thank you.

**Comment by Gregwar** [comment]
Hello
This is great!
If you mind opening a PR adding a section with relevant information in the README of this repository I'll merge it

**Comment by juliardi** [comment]
I've opening a PR here #50. Please review it.

**Comment by Gregwar** [comment]
I merged the PR, the note is now in the README!
