### ISSUE TITLE
bug count() php 7.2

### ISSUE THREAD

**Issue by andreybolonin** [Gregwar/Captcha#53]
<img width="828" alt="screen shot 2017-12-01 at 3 22 10 pm" src="https://user-images.githubusercontent.com/2576509/33484568-87b7d34a-d6ab-11e7-8dff-53dab95b8dcc.png">

PHP 7.2
Symfony 3.4
CaptchaBundle 2.0.3

What about to create new release with this https://github.com/Gregwar/Captcha/commit/db934bae040e72999f0a31333c3ed48f0250b638 patch ?

**Comment by Gregwar** [comment]
Tagged `v1.1.4`, is it ok for you?

**Comment by andreybolonin** [comment]
thx!
