### ISSUE TITLE
Release for symfony 4.x support

### ISSUE THREAD

**Issue by andreybolonin** [Gregwar/Captcha#56]
<img width="394" alt="screen shot 2018-01-06 at 5 43 51 pm" src="https://user-images.githubusercontent.com/2576509/34641207-2f35499e-f309-11e7-8871-907d6d1657bf.png">

@Gregwar can you create new release?
wich include https://github.com/Gregwar/Captcha/commit/1d06ac8e12d2b3e0df39586d78b9f50e086a0bea
thx

**Comment by Gregwar** [comment]
I tagged `v1.1.5`, is it ok for you?
Sorry for the delay

**Comment by andreybolonin** [comment]
@Gregwar very big thx
