### ISSUE TITLE
Why Finder 3.0 ?

### ISSUE THREAD

**Issue by nkornev** [Gregwar/Captcha#64]
Is there anything that prevents it from working with Finder 2.8?

I am using this package through `gregwar/captcha-bundle`, which will work with Symfony 2.8. However, `gregwar/captcha` requires Finder 3.0 or above. As the result, I get `gregwar/captcha v1.1.3` which is not compatible with PHP 7, while Symfony 2.8 is.

**Comment by Gregwar** [comment]
I agree that this dependency could be loosened, maybe even to a star since we only use the very core of the finder in a really specific function

**Comment by Gregwar** [comment]
I loosened the dependency and tagged `v1.1.7`, is it ok for you?

**Comment by nkornev** [comment]
That would definitely work. Already updated.

Thank you for prompt response!

**Comment by ZhangChengLin** [comment]
Now what?

```
https://packagist.org/packages/symfony/finder#5.3.x-dev

5.3.x-dev  2021-08-04 21:20 UTC
requires

php: >=7.2.5
symfony/polyfill-php80: ^1.16
```
